spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: skillbox
    password: skillbox
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
    drop-first: false


